name: 'Translations actions'
description: 'Here we run Actions for translations such as push/pull with/without email templates.'
inputs:
  service-host:
    description: 'Translation service endpoint'
    required: true
  trigger-type:
    description: "The type of a action: either `push' or `pull'. The default value is `push'."
    default: push
    required: true
  project-type:
    description: "The type of a project: either `i18n' or `documents'. The default value is `i18n'."
    default: i18n
    required: true
  create-pr:
    description: 'When pulling translation from the dedicated service, this option allows creating a PR to the service repository.'
    default: false
    required: false

runs:
  using: composite
  steps:
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DATLE_DEBUG_KEY }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        # cache: 'npm'
        # cache-dependency-path: ${{ github.action_path }}/scripts/package-lock.json
    - name: Install prerequisites
      shell: bash
      run: npm i -g zx@4.2.0 form-data@4.0.0
    - name: Run push
      shell: bash
      run: zx ${{ github.action_path }}/scripts/${{ inputs.trigger-type }}_${{ inputs.project-type }}.mjs
      env:
        SERVICE_HOST: ${{ inputs.service-host }}
    # - name: Run create PR

